# ros_control_namespace: /yumi/egm
controller_list:
  - name: left_arm
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - yumi_robl_joint_1
      - yumi_robl_joint_2
      - yumi_robl_joint_3
      - yumi_robl_joint_4
      - yumi_robl_joint_5
      - yumi_robl_joint_6
      - yumi_robl_joint_7
  - name: right_arm
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - yumi_robr_joint_1
      - yumi_robr_joint_2
      - yumi_robr_joint_3
      - yumi_robr_joint_4
      - yumi_robr_joint_5
      - yumi_robr_joint_6
      - yumi_robr_joint_7
  - name: both_arms
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - yumi_robl_joint_1
      - yumi_robl_joint_2
      - yumi_robl_joint_3
      - yumi_robl_joint_4
      - yumi_robl_joint_5
      - yumi_robl_joint_6
      - yumi_robl_joint_7
      - yumi_robr_joint_1
      - yumi_robr_joint_2
      - yumi_robr_joint_3
      - yumi_robr_joint_4
      - yumi_robr_joint_5
      - yumi_robr_joint_6
      - yumi_robr_joint_7

  # - name: /yumi/egm/joint_group_velocity_controller
  #   type: velocity_controllers/JointGroupVelocityController
  #   action_ns: command
  #   joints:
  #     - yumi_robl_joint_1
  #     - yumi_robl_joint_2
  #     - yumi_robl_joint_3
  #     - yumi_robl_joint_4
  #     - yumi_robl_joint_5
  #     - yumi_robl_joint_6
  #     - yumi_robl_joint_7
  #     - yumi_robr_joint_1
  #     - yumi_robr_joint_2
  #     - yumi_robr_joint_3
  #     - yumi_robr_joint_4
  #     - yumi_robr_joint_5
  #     - yumi_robr_joint_6
  #     - yumi_robr_joint_7

  # - name: /yumi/egm/jnt_traj_vel_controller_l
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   joints:
  #     - yumi_robl_joint_1
  #     - yumi_robl_joint_2
  #     - yumi_robl_joint_3
  #     - yumi_robl_joint_4
  #     - yumi_robl_joint_5
  #     - yumi_robl_joint_6
  #     - yumi_robl_joint_7

  # - name: /yumi/egm/jnt_traj_vel_controller_r
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   joints:
  #     - yumi_robr_joint_1
  #     - yumi_robr_joint_2
  #     - yumi_robr_joint_3
  #     - yumi_robr_joint_4
  #     - yumi_robr_joint_5
  #     - yumi_robr_joint_6
  #     - yumi_robr_joint_7
  
  # - name: /yumi/egm/jnt_traj_pos_controller_l
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   joints:
  #     - yumi_robl_joint_1
  #     - yumi_robl_joint_2
  #     - yumi_robl_joint_3
  #     - yumi_robl_joint_4
  #     - yumi_robl_joint_5
  #     - yumi_robl_joint_6
  #     - yumi_robl_joint_7

  # - name: /yumi/egm/jnt_traj_pos_controller_r
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   joints:
  #     - yumi_robr_joint_1
  #     - yumi_robr_joint_2
  #     - yumi_robr_joint_3
  #     - yumi_robr_joint_4
  #     - yumi_robr_joint_5
  #     - yumi_robr_joint_6
  #     - yumi_robr_joint_7

  # - name: /yumi/egm/jnt_traj_pos_controller
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   joints:
  #     - yumi_robl_joint_1
  #     - yumi_robl_joint_2
  #     - yumi_robl_joint_3
  #     - yumi_robl_joint_4
  #     - yumi_robl_joint_5
  #     - yumi_robl_joint_6
  #     - yumi_robl_joint_7
  #     - yumi_robr_joint_1
  #     - yumi_robr_joint_2
  #     - yumi_robr_joint_3
  #     - yumi_robr_joint_4
  #     - yumi_robr_joint_5
  #     - yumi_robr_joint_6
  #     - yumi_robr_joint_7