# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  yumi_robl_joint_1:
    min_position: -2.84
    max_position: 2.84
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_2:
    min_position: -2.4
    max_position: 0.65
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_3:
    min_position: -2.84
    max_position: 2.84
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_4:
    min_position: -2
    max_position: 1.29
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_5:
    min_position: -4.9
    max_position: 4.9
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_6:
    min_position: -1.43
    max_position: 2.3
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_7:
    min_position: -3.89
    max_position: 3.89
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_1:
    min_position: -2.84
    max_position: 2.84
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_2:
    min_position: -2.4
    max_position: 0.65
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_3:
    min_position: -2.84
    max_position: 2.84
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_4:
    min_position: -2
    max_position: 1.29
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_5:
    min_position: -4.9
    max_position: 4.9
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_6:
    min_position: -1.43
    max_position: 2.3
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_7:
    min_position: -3.89
    max_position: 3.89
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
    has_velocity_limits: false
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_r_joint_m:
    has_velocity_limits: false
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_1:
    min_position: -2.84
    max_position: 2.84
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_2:
    min_position: -2.4
    max_position: 0.65
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_3:
    min_position: -2.84
    max_position: 2.84
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_4:
    min_position: -2
    max_position: 1.29
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_5:
    min_position: -4.9
    max_position: 4.9
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_6:
    min_position: -1.43
    max_position: 2.3
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_7:
    min_position: -3.89
    max_position: 3.89
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_1:
    min_position: -2.84
    max_position: 2.84
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_2:
    min_position: -2.4
    max_position: 0.65
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_3:
    min_position: -2.84
    max_position: 2.84
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_4:
    min_position: -2
    max_position: 1.29
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_5:
    min_position: -4.9
    max_position: 4.9
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_6:
    min_position: -1.43
    max_position: 2.3
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_7:
    min_position: -3.89
    max_position: 3.89
    has_velocity_limits: true
    max_velocity: 6.981317007977318
    has_acceleration_limits: false
    max_acceleration: 0