# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

joint_pos_controller_1_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_robl_joint_1
joint_pos_controller_2_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_robl_joint_2
joint_pos_controller_7_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_robl_joint_7
joint_pos_controller_3_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_robl_joint_3
joint_pos_controller_4_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_robl_joint_4
joint_pos_controller_5_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_robl_joint_5
joint_pos_controller_6_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_robl_joint_6
joint_pos_controller_1_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_robr_joint_1
joint_pos_controller_2_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_robr_joint_2
joint_pos_controller_7_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_robr_joint_7
joint_pos_controller_3_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_robr_joint_3
joint_pos_controller_4_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_robr_joint_4
joint_pos_controller_5_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_robr_joint_5
joint_pos_controller_6_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_robr_joint_6



joint_group_pos_controller_l:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - yumi_robl_joint_1
    - yumi_robl_joint_2
    - yumi_robl_joint_7
    - yumi_robl_joint_3
    - yumi_robl_joint_4
    - yumi_robl_joint_5
    - yumi_robl_joint_6
  gains:
    yumi_robl_joint_1: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_2: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_7: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_3: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_4: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_5: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_6: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
  constraints:
    goal_time: 1
  stop_trajectory_duration: 0


joint_group_pos_controller_r:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - yumi_robr_joint_1
    - yumi_robr_joint_2
    - yumi_robr_joint_7
    - yumi_robr_joint_3
    - yumi_robr_joint_4
    - yumi_robr_joint_5
    - yumi_robr_joint_6
  gains:
    yumi_robr_joint_1: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_2: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_7: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_3: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_4: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_5: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_6: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
  constraints:
    goal_time: 1
  stop_trajectory_duration: 0
    
